(cl:defpackage lgsvl_msgs-msg
  (:use )
  (:export
   "<BOUNDINGBOX2D>"
   "BOUNDINGBOX2D"
   "<BOUNDINGBOX3D>"
   "BOUNDINGBOX3D"
   "<DETECTION2D>"
   "DETECTION2D"
   "<DETECTION2DARRAY>"
   "DETECTION2DARRAY"
   "<DETECTION3D>"
   "DETECTION3D"
   "<DETECTION3DARRAY>"
   "DETECTION3DARRAY"
  ))

